In [60]:
import numpy as np
s = np.array([[1,2,3], [4,5,6]])
s.shape

(2, 3)

In [61]:
s

array([[1, 2, 3],
       [4, 5, 6]])

In [62]:
s.reshape(6)

array([1, 2, 3, 4, 5, 6])

In [63]:
s.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [64]:
# Elementwise multiply
np.multiply(s, s)

array([[ 1,  4,  9],
       [16, 25, 36]])

In [65]:
# Dot product
np.matmul(s, s.T)

array([[14, 32],
       [32, 77]])

In [68]:
# Example
inputs = np.array([[-0.27,  0.45,  0.64, 0.31]])
weights = np.array([[0.02, 0.001, -0.03, 0.036], \
    [0.04, -0.003, 0.025, 0.009], [0.012, -0.045, 0.28, -0.067]])
np.matmul(inputs, weights.T)

array([[-0.01299,  0.00664,  0.13494]])

In [84]:
# Use the numpy library
import numpy as np


def prepare_inputs(inputs):
    # TODO: create a 2-dimensional ndarray from the given 1-dimensional list;
    #       assign it to input_array
    input_array = np.array([inputs, inputs])
    
    # TODO: find the minimum value in input_array and subtract that
    #       value from all the elements of input_array. Store the
    #       result in inputs_minus_min
    inputs_minus_min = input_array - input_array.min()

    # TODO: find the maximum value in inputs_minus_min and divide
    #       all of the values in inputs_minus_min by the maximum value.
    #       Store the results in inputs_div_max.
    inputs_div_max = inputs_minus_min / inputs_minus_min.max()

    # return the three arrays we've created
    return input_array, inputs_minus_min, inputs_div_max
    

def multiply_inputs(m1, m2):
    # TODO: Check the shapes of the matrices m1 and m2. 
    #       m1 and m2 will be ndarray objects.
    #
    #       Return False if the shapes cannot be used for matrix
    #       multiplication. You may not use a transpose
    if m1.shape[1] != m2.shape[0]:
        return False


    # TODO: If you have not returned False, then calculate the matrix product
    #       of m1 and m2 and return it. Do not use a transpose,
    #       but you swap their order if necessary
    return np.matmul(m1, m2)
    

def find_mean(values):
    # TODO: Return the average of the values in the given Python list
    return np.average(values)


input_array, inputs_minus_min, inputs_div_max = prepare_inputs([-1,2,7])
print("Input as Array: {}".format(input_array))
print("Input minus min: {}".format(inputs_minus_min))
print("Input  Array: {}".format(inputs_div_max))

print("Multiply 1:\n{}".format(multiply_inputs(np.array([[1,2,3],[4,5,6]]), np.array([[1],[2],[3],[4]]))))
print("Multiply 2:\n{}".format(multiply_inputs(np.array([[1,2,3],[4,5,6]]), np.array([[1],[2],[3]]))))
print("Multiply 3:\n{}".format(multiply_inputs(np.array([[1,2,3],[4,5,6]]), np.array([[1,2]]))))

print("Mean == {}".format(find_mean([1,3,4])))

Input as Array: [[-1  2  7]
 [-1  2  7]]
Input minus min: [[0 3 8]
 [0 3 8]]
Input  Array: [[ 0.     0.375  1.   ]
 [ 0.     0.375  1.   ]]
Multiply 1:
False
Multiply 2:
[[14]
 [32]]
Multiply 3:
False
Mean == 2.6666666666666665


1